### ISSUE TITLE
Cannot be easily reproduced

### ISSUE THREAD

**Issue by gaozheng2001** [lukebhan/NeuralOperatorsForAdvectionDiffusionControl#1]
### Cannot be easily reproduced

Platform:
- Ubuntu 22.04.4 LTS
- Python 3.12.3
- pytorch 2.5.1+cu118
- DeepXDE 1.12.2
- GPU NVIDIA GeForce RTX 4090 

When I trained the model from scratch (generating a new dataset and training it), I didn’t get convergence and I don’t know what went wrong.

I mainly changed the number of training steps for the model (500->20000, which actually made no difference)

Here is my code and output

[parabolicMapping.pdf](https://github.com/user-attachments/files/17939407/parabolicMapping.pdf)

**Comment by lukebhan** [comment]
Hi, 
Thanks for checking out our result. It looks to me like the kernel shape is close, but not quite correct. I went through my code and found a small mistake. In block [5],line 14 of the PDF you attached, the generation code has the following lambda calculation
`
lam[j] = 20*math.cos(lamArr[i]*math.acos(spatial[j]))
`
However, in block[15], 6th line, the lambda used in the plant is given by 
`
lam[j] = 50*math.cos(lamarr[i]*math.acos(spatial[j]))
` 
Notice, the difference between 50 and 20 on the scaling before the math.cos call. So the neural operator was trained for lambda on a scale of 20 and it is being tested on a scale of 50. This is my mistake completely and so to fix this, there are two options. One, keep your model as is and change the block[15] 6th line code to 
`
lam[j] = 20*math.cos(lamArr[i]*math.acos(spatial[j]))
`
The other option is to regenerate new data changing the block 6 datagen code to 
`
lam[j] = 50*math.cos(lamarr[i]*math.acos(spatial[j]))
` 
and retrain. The results in the paper will match the latter option, namely with the value set as 50. I have gone ahead and modified the library to reflect this change. Let me know if this solves the issue and happy to help if you have more questions.

**Comment by gaozheng2001** [comment]
Thank you very much for your reply. Based on your tips, I modified the corresponding code and was able to successfully reproduce your results.
